/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FAC_H_RPCGEN
#define _FAC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct facArgs {
	int x;
	int y;
};
typedef struct facArgs facArgs;

#define FAC_PROG 0x23451111
#define FAC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define calcFac 1
extern  int * calcfac_1(int *, CLIENT *);
extern  int * calcfac_1_svc(int *, struct svc_req *);
#define calcMult 2
extern  int * calcmult_1(facArgs *, CLIENT *);
extern  int * calcmult_1_svc(facArgs *, struct svc_req *);
extern int fac_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calcFac 1
extern  int * calcfac_1();
extern  int * calcfac_1_svc();
#define calcMult 2
extern  int * calcmult_1();
extern  int * calcmult_1_svc();
extern int fac_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_facArgs (XDR *, facArgs*);

#else /* K&R C */
extern bool_t xdr_facArgs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FAC_H_RPCGEN */
