/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fac.h"

int *
calcfac_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	result = 1;
	for (int i = 1; i < *argp; ++i) {
		result *= i;
	}
	return &result;
}

int *
calcmult_1_svc(facArgs *argp, struct svc_req *rqstp)
{
	static int result;
	result = argp->x * argp->y;
	return &result;
}
