/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fac.h"

bool_t
xdr_facArgs (XDR *xdrs, facArgs *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}
