/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct two_ints {
	int a;
	int b;
};
typedef struct two_ints two_ints;

#define CALC_PROG 0x31234567
#define CALC_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(two_ints *, CLIENT *);
extern  int * add_1_svc(two_ints *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_two_ints (XDR *, two_ints*);

#else /* K&R C */
extern bool_t xdr_two_ints ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
